version: '2'
services:
  sparender:
    build: .
    ports: 
      - "8082:8082"
    volumes:
      - "./cache:/home/cache"
    links:
      - selenium
  selenium:
    image: "selenium/standalone-chrome"
    ports:
      - "4444:4444"
    extra_hosts:
       - "www.google-analytics.com:127.0.0.1"
